name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: github/super-linter@v4
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: lint
    environment: default
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/trails
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          file: Dockerfile
          push: true
          target: app
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/trails:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/trails:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.build.outputs.digest }}

  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    needs: [lint, build]
    environment: default
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [lint, build, analyze]
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: release-please-action
