name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    environment: default
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-20.04
    environment: default
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            registry.hub.docker.com/acchiao/trails
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule
            type=semver,pattern=v{{version}}
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=sha,prefix=,suffix=,format=long
            type=sha,prefix=,suffix=,format=short
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          target: app
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.build.outputs.digest }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-20.04
    needs: [build]
    environment: default
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ javascript ]
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1

  brakeman:
    name: Brakeman
    runs-on: ubuntu-20.04
    needs: [build]
    environment: default
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: |
        gem install brakeman --version $BRAKEMAN_VERSION
      env:
        BRAKEMAN_VERSION: 5.1
    - run: |
        brakeman -f sarif -o output.sarif.json .
      continue-on-error: true
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: output.sarif.json

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [build, codeql, brakeman]
    environment: default
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: release-please-action
