name: CI

on: [push, pull_request, pull_request_target, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  PROJECT_NAME: trails

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          DEFAULT_BRANCH: main
          DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  manifests:
    name: Manifests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: azure/setup-helm@v3
        with:
          version: 3.8.0
      - uses: helm/kind-action@v1.5.0
      - run: |
          helm lint charts/trails
          helm install test charts/trails
      - name: kube-score
        continue-on-error: true
        run: |
          helm template charts/trails > template.yaml
          wget --no-verbose --show-progress --progress dot:giga https://github.com/zegl/kube-score/releases/download/v1.13.0/kube-score_1.13.0_linux_amd64.tar.gz
          echo "e8b739c932ff8505ba80bb58e4e1a244c79caa9816f3db78171253634114c022  kube-score_1.13.0_linux_amd64.tar.gz" | sha256sum --check
          tar xf kube-score_1.13.0_linux_amd64.tar.gz
          ./kube-score score --output-format ci --kubernetes-version 1.22 template.yaml

  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, production]
    environment:
      name: ${{ matrix.environment }}
      url: https://localhost:3000
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            registry.hub.docker.com/${{ secrets.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=sha,prefix=,suffix=,format=long
            type=sha,prefix=,suffix=,format=short
            type=raw,value=${{ matrix.environment }}
      - uses: docker/build-push-action@v5.1.0
        id: build
        with:
          context: .
          file: Dockerfile
          push: true
          target: ${{ matrix.environment }}
          cache-from: type=registry,ref=registry.hub.docker.com/${{ secrets.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:buildcache
          cache-to: type=registry,ref=registry.hub.docker.com/${{ secrets.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.build.outputs.digest }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-20.04
    # needs: [build]
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [javascript]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1

  brakeman:
    name: Brakeman
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: |
          gem install brakeman --version $BRAKEMAN_VERSION
          brakeman --format sarif --output output.sarif.json .
        env:
          BRAKEMAN_VERSION: 5.2.1
      # - uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: output.sarif.json
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: output.sarif.json
      #     path: output.sarif.json
      #     if-no-files-found: warn
      #     retention-days: 90

  rubocop:
    name: RuboCop
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
      - run: |
          bundle add code-scanning-rubocop --skip-install
          bundle install
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
            [[ $? -ne 2 ]]
          "
      # - uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: rubocop.sarif
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: rubocop.sarif
      #     path: rubocop.sarif
      #     if-no-files-found: warn
      #     retention-days: 90

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [build, codeql, brakeman, rubocop, manifests, lint]
    if: ${{ github.ref == 'refs/heads/main' }}
    # if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: googlecloudplatform/release-please-action@v4
        with:
          release-type: simple
          package-name: release-please-action
